name: Main Pull Request merged workflow

on:
  pull_request:
    branches:
     - main
     - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Unit Test
      run: |
        go test ./...

